---
log_level: debug
auth:
  cloudflare:
    email: foo@bar.com
    key: abcdef
  ovh:
    app_key: abcdef
    app_secret: abcdef
    consumer_key: abcdef
checks:
  base_domain: bar.com
  # supported values: hourly, daily, weekly, monthly
  frequency: weekly
  domains:
    - www.bar.com
    - blog.bar.com
    - www.staging.bar.com
    - blog.staging.bar.com