name: GolangCI Linter
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.18"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          install-mode: binary
          # --timeout is the timeout for total work
          args: --timeout=5m
